package com.example.demo.model;
// Generated 13 de dez. de 2021 12:43:57 by Hibernate Tools 5.5.7.Final

/**
 * Administrador generated by hbm2java
 */
public class Administrador implements java.io.Serializable {

	private String usuarioLogin;
	private Usuario usuario;
	private Integer codAdm;

	public Administrador() {
	}

	public Administrador(Usuario usuario) {
		this.usuario = usuario;
	}

	public Administrador(Usuario usuario, Integer codAdm) {
		this.usuario = usuario;
		this.codAdm = codAdm;
	}

	public String getUsuarioLogin() {
		return this.usuarioLogin;
	}

	public void setUsuarioLogin(String usuarioLogin) {
		this.usuarioLogin = usuarioLogin;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Integer getCodAdm() {
		return this.codAdm;
	}

	public void setCodAdm(Integer codAdm) {
		this.codAdm = codAdm;
	}

}
