package com.example.demo.model;
// Generated 13 de dez. de 2021 12:43:57 by Hibernate Tools 5.5.7.Final

/**
 * Professor generated by hbm2java
 */
public class Professor implements java.io.Serializable {

	private String usuarioLogin;
	private Usuario usuario;
	private Integer codProfessor;

	public Professor() {
	}

	public Professor(Usuario usuario) {
		this.usuario = usuario;
	}

	public Professor(Usuario usuario, Integer codProfessor) {
		this.usuario = usuario;
		this.codProfessor = codProfessor;
	}

	public String getUsuarioLogin() {
		return this.usuarioLogin;
	}

	public void setUsuarioLogin(String usuarioLogin) {
		this.usuarioLogin = usuarioLogin;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Integer getCodProfessor() {
		return this.codProfessor;
	}

	public void setCodProfessor(Integer codProfessor) {
		this.codProfessor = codProfessor;
	}

}
