package com.example.demo.model;
// Generated 13 de dez. de 2021 12:43:57 by Hibernate Tools 5.5.7.Final

/**
 * Sala generated by hbm2java
 */
public class Sala implements java.io.Serializable {

	private int codSala;
	private String turma;

	public Sala() {
	}

	public Sala(int codSala) {
		this.codSala = codSala;
	}

	public Sala(int codSala, String turma) {
		this.codSala = codSala;
		this.turma = turma;
	}

	public int getCodSala() {
		return this.codSala;
	}

	public void setCodSala(int codSala) {
		this.codSala = codSala;
	}

	public String getTurma() {
		return this.turma;
	}

	public void setTurma(String turma) {
		this.turma = turma;
	}

}
